### ISSUE TITLE
.0.0.3 error windows 10

### ISSUE THREAD

**Issue by fittsy** [zencashio/eleos#8]
.0.0.3 won't run on windows 10.

Tried upgrading from .0.0.2 got error.
uninstalled.
rebooted.
tried fresh install of .0.0.3. Same error when trying to run Eleos.

![eleos_error](https://cloud.githubusercontent.com/assets/26425176/25145861/c8854d2a-2437-11e7-92c6-2c9bc7dad240.png)

**Comment by joshuayabut** [comment]
Try installing v0.0.4 version and let me know if you still get this error.

**Comment by fittsy** [comment]
Hey Joshua, it works better. Like it installs and I can run it. But I don't seem to get a console window when I click on console.

Win 10. Fresh install, only a week old.

**Comment by fittsy** [comment]
If I had to guess the issue is when I install it ends up with a blank config file.  Where the windows classic has a config file that comes loaded with rpc user, pass, and lots of nodes.

Perhaps this is a bug because I installed to I:\ instead of C:\ and the program wasn't able to write the inital config?  I see a config but it's mostly blank values like this:

{
    "coin": "zcl",
    "rpcUser": "",
    "rpcPass": "",
    "rpcIP": "",
    "rpcPort": "",
    "binaryPathWin": "",
    "binaryPathMacOS": "",
    "binaryPathLinux": "",
    "confPathWin": "",
    "confPathMacOS": "",
    "confPathLinux": ""
}

**Comment by fittsy** [comment]
FYI - I manually entered rpcuser, rpcpass, rpcip, and rpcport to where the windows classic wallet points. Then restarted Eliod and everything worked fine.

**Comment by LukasBures** [comment]
Could be closed.

**Comment by fittsy** [comment]
No I still got the error on .0.0.4.  Are you sure this has been fixed in the new version?

**Comment by tarrenj** [comment]
@fittsy Have you tested this with 0.0.6?

**Comment by LukasBures** [comment]
He told me yesterday, that he tried it and still not working for him
